import Head from 'next/head';
import dynamic from 'next/dynamic';
import Header from '@/components/header/header';
import s from '@/styles/index.module.scss';
import { GreetingSection } from '@/sections/greetingSection/greetingSection';
import { useEffect, useState } from 'react';
import { Player } from '@/components/player/player';
import { api } from '@/common/api';
import { ContactsData } from '@/common/types';

//next/dynamic imports
const MainSection = dynamic(() => import('../sections/1-mainSection/mainSection'));
const CatalogSection = dynamic(() => import('../sections/3-catalogSection/catalogSection'));
const ProjectMapSection = dynamic(
  () => import('../sections/4-projectMapSection/projectMapSection'),
);
const AboutSection = dynamic(() => import('../sections/2-aboutSection/aboutSection'));
const FAQ = dynamic(() => import('../sections/6-faqSection/faq'));
const FormSection = dynamic(() => import('../sections/7-formSection/formSection'));
const DocumentationSection = dynamic(
  () => import('../sections/8-documentationSection/documentationSection'),
);
const Footer = dynamic(() => import('../components/footer/footer'));

export const getStaticProps = async () => {
  const contactInfo = await api.getContacts();
  return { props: { contactInfo } };
};

type HomeProps = {
  contactInfo: ContactsData;
};

export default function Home(props: HomeProps) {
  const { contactInfo } = props;
  const [showGreeting, setShowGreeting] = useState(true);
  const [initialPlaying, setInitialPlaying] = useState(false);

  return (
    <>
      <Head>
        <title>Калейдоскоп игр</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>
      <div className='mainContainer'>
        {showGreeting && (
          <GreetingSection
            setShowGreeting={setShowGreeting}
            setPlaying={setInitialPlaying}
            className={!showGreeting ? s.hiddenGreeting : ''}
          />
        )}
        <Header
          className={s.header}
          player={<Player initialPlaying={initialPlaying} key={`playing-${initialPlaying}`} />}
        />

        {!showGreeting && (
          <>
            <MainSection />
            <AboutSection />
            <CatalogSection />
            <ProjectMapSection />
            <FAQ />
            <FormSection />
            <DocumentationSection />
            <Footer
              tels={contactInfo['contact_phones']}
              emails={contactInfo['contact_emails']}
              socialLinks={contactInfo['social_links']}
            />
          </>
        )}
      </div>
    </>
  );
}
